### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by ornyilmaz** [myriadrf/LimeSDR-USB#17]
How can I use the LimeSDR-USB with android tablet? Do you planned android driver? Because android tablets very powerful this days.

**Comment by 9600** [comment]
All LimeSDR hardware is supported by [Lime Suite](https://github.com/myriadrf/LimeSuite) and for any issues related to the driver, please raise these via its tracker, rather than here, which is for the hardware design.

ISTR some have built Lime Suite on Android, since the underlying O/S is Linux. There are no plans at present for any Android-specific features or packaging etc.

**Comment by ornyilmaz** [comment]
Thank you for your reply.
