### ISSUE TITLE
Repository authority?

### ISSUE THREAD

**Issue by alexwhittemore** [myriadrf/LimeSDR-USB#4]
I'm guessing this repo is curated to be public-facing and doesn't represent whatever internal version control is being used in active development? The real thrust of my question is whether it's worth forking, contributing, and pull-requesting, or if this repository is going to be non-authoritative for the purpose of shielding intermediate development from the public. Are there plans to use this repo for active development in the future, or is it always likely to be a limited-commit public face?

**Comment by 9600** [comment]
Good question! The plan is very much for these to be the authoritative/master repos and pull requests are encouraged — we'd love to have contributions to improving the platform. We obviously need to have at least some sort of basic policy in place and this is something that we hope to announce in the not too distant future.

**Comment by alexwhittemore** [comment]
Great to hear! Although that does raise some concerns about _how_ community members can contribute, given that the project is designed in Altium. CircuitMaker, in Altium's closed-ecosystem wisdom, won't open offline projects, and the $10k/seat price tag of AD16 is going to keep non-professionals away. As it happens, I personally use Altium on a daily basis at work, but then there's still the question of using corporate resources for open source contributions, which I imagine will be a hangup for many. On the one hand, this may effectively filter contributions to only professional engineers. On the other hand, that may well not be what you actually want. Thoughts on addressing those kinds of issues?

**Comment by 9600** [comment]
If you look at the majority of the other Myriad-RF projects you will see that KiCAD databases have been published for them. It's always been the plan to make LimeSDR available as a KiCAD design also and it's just a question of time and resources (which are currently focused on the driver, apps and campaign etc.)

**Comment by alexwhittemore** [comment]
Ahh, I hadn't actually dug in enough to see that. So I suppose, follow-on question, at such a time as you have resources to pay off the technical debt of converting over, presumably the replacement KiCad projects become canonical?

**Comment by 9600** [comment]
Good question and we might need to figure out a practical workflow to support contributions. For example, KiCAD will lack certain features that are highly beneficial when doing impedance matched RF layout, and so then how would you "round trip" the design between two tools? But perhaps more than this, we'll need to figure out what the criteria are for accepting pull requests that update the hardware design.

Updates to the hardware platform are obviously very different to updates to the host driver, FX3 and FPGA firmware, since there are very different implications, notably the cost involved in validation/testing and manufacturing. I could, for example, imagine a situation whereby we might have a branch with a derivative design of some merit, that has not been validated — i.e. physically built and put through its paces — by Lime Micro. However, others would be at liberty to do this. But then if someone proposes a great and eminently practical improvement to the hardware platform, it would clearly make sense to try and incorporate this.
